# ===== قاعدة البيانات =====
spring.datasource.url=jdbc:postgresql://localhost:5432/mufakkira_db
spring.datasource.username=mufakkira_user
spring.datasource.password=sA4bt90WbI2/UGVAEZahqKMgDsocdOos6HWGI/AvEro=
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===== السيرفر =====
server.port=8080

# ===== JWT =====
app.jwt.secret=crRbXyQ9no+3pvAJgxKVusAisHWUTCTtb1Ytz5op6Vy2TmpBC+c7DdzWSMyYHSbn/lp0Va7qfO1eDe5Gvuu8OQ==
app.jwt.expiration=86400000

# ===== CORS — يسمح للـ Frontend يتكلم مع الـ Backend =====
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:5500}

sendgrid.api.key=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
sendgrid.from.email=nawaaf042@gmail.com